name: scRNA_seq
channels:
  - conda-forge
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - anndata=0.10.9=pyhd8ed1ab_0
  - arpack=3.9.1=nompi_h77f6705_101
  - array-api-compat=1.9=pyhd8ed1ab_0
  - binutils_impl_linux-64=2.43=h4bf12b8_2
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.2=heb4867d_0
  - ca-certificates=2024.8.30=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=hebfffa5_3
  - certifi=2024.8.30=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.3.0=py312h68727a3_2
  - curl=8.10.1=hbbe4b11_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - expat=2.6.3=h5888daf_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.54.1=py312h178313f_1
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=14.2.0=h6b349bd_1
  - get-annotations=0.1.2=pyhd8ed1ab_0
  - gfortran_impl_linux-64=14.2.0=hc73f493_1
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.13=h59595ed_1003
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=14.2.0=h2c03514_1
  - h5py=3.12.1=nompi_py312hedeef09_102
  - harfbuzz=9.0.0=hda332d3_1
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - icu=75.1=he02047a_0
  - igraph=0.10.13=hef0740d_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - kernel-headers_linux-64=3.10.0=he073ed8_17
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py312h68727a3_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - legacy-api-wrap=1.4=pyhd8ed1ab_1
  - leidenalg=0.10.2=py312h30efb56_0
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.3=h59595ed_0
  - libblas=3.9.0=25_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=25_linux64_openblas
  - libcurl=8.10.1=hbbe4b11_0
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=14.2.0=h41c2201_101
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.82.2=h2ff4ddf_0
  - libgomp=14.2.0=h77fa898_1
  - libhwloc=2.11.1=default_hecaa2ac_1000
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=25_linux64_openblas
  - libleidenalg=0.11.1=h00ab1b0_0
  - libllvm14=14.0.6=hcd5def8_4
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.28=pthreads_h94d23a6_0
  - libpng=1.6.44=hadc24fc_0
  - libsanitizer=14.2.0=h2a3dede_1
  - libsqlite=3.47.0=hadc24fc_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=14.2.0=h41c2201_101
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.7.0=he137b08_1
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=he7c6b58_4
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.43.0=py312h374181b_1
  - make=4.4.1=hb9d3cd8_2
  - matplotlib-base=3.9.2=py312hd3ec401_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - natsort=8.4.0=pyhd8ed1ab_0
  - ncurses=6.5=he02047a_1
  - networkx=3.4.2=pyhd8ed1ab_0
  - numba=0.60.0=py312h83e6fd3_0
  - numpy=2.0.2=py312h58c1407_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.3=py312hf9745cd_1
  - pango=1.54.0=h4c5309f_1
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.44=hba22ea6_2
  - pillow=11.0.0=py312h7b63e92_0
  - pip=24.2=pyh8b19718_1
  - pixman=0.43.2=h59595ed_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pynndescent=0.5.13=pyhff2d567_0
  - pyparsing=3.2.0=pyhd8ed1ab_1
  - python=3.12.7=hc5c86c4_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-igraph=0.11.6=py312h3262465_2
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - r-base=4.4.1=h64c9cd0_16
  - readline=8.2=h8228510_1
  - scanpy=1.10.3=pyhd8ed1ab_0
  - scikit-learn=1.5.2=py312h7a48858_1
  - scipy=1.14.1=py312h62794b6_1
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - sed=4.8=he412f7d_0
  - session-info=1.0.0=pyhd8ed1ab_0
  - setuptools=75.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - statsmodels=0.14.4=py312hc0a28a1_0
  - stdlib-list=0.11.0=pyhd8ed1ab_0
  - sysroot_linux-64=2.17=h4a8ded7_17
  - tbb=2021.13.0=h84d6215_0
  - texttable=1.7.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h8bc8fbc_6
  - tqdm=4.66.5=pyhd8ed1ab_0
  - tzdata=2024b=hc8b5060_0
  - umap-learn=0.5.6=py312h7900ff3_1
  - unicodedata2=15.1.0=py312h66e93f0_1
  - wheel=0.44.0=pyhd8ed1ab_0
  - xorg-libice=1.1.1=hb9d3cd8_1
  - xorg-libsm=1.2.4=he73a12e_1
  - xorg-libx11=1.8.10=h4f16b4b_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.11=hb9d3cd8_1
  - xorg-libxt=1.3.0=hb9d3cd8_2
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xz=5.2.6=h166bdaf_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.6=ha6fb4c9_0

